# Generated by Django 3.2.14 on 2022-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapp', '0005_hotelpicturesmodel_remove_hotellist_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature1HotelSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, default='-', max_length=250)),
                ('hotel_id', models.CharField(blank=True, default='-', max_length=250)),
                ('dest_id', models.CharField(blank=True, default='-', max_length=250)),
                ('guests_number', models.PositiveIntegerField(blank=True, default=3)),
                ('rooms_number', models.PositiveIntegerField(blank=True, default=3)),
                ('start_date', models.DateField(blank=True, default='2020-10-10')),
                ('end_date', models.DateField(blank=True, default='2020-11-11')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='bank',
            field=models.CharField(choices=[('DBS', 'DBS'), ('OCBC', 'OCBC'), ('HSBC', 'HSBC'), ('Credit Suisse', 'Credit Suisse'), ('American Express', 'American Express')], default='green', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_key',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='credit_card_no',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='feature1',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature1',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
